#------------------------------------------------------------
#Configuration file of Roleplay Utilities by Manfry
#For helpstaff, this is my Discord id: Manfry#8538
#------------------------------------------------------------

#------------------------------------------------------------
#Broadcast module
#alias: /bc /a /annuncio
#------------------------------------------------------------

#true for enabled and false for disabilitate
enabled-bc: true
prefix-bc: "&c&lMESSAGE &8▶ &c"
broadcast-send: "You sent a broadcast!"

#------------------------------------------------------------
#helpstaff module
#alias: /aiuto /helpstaff /a
#------------------------------------------------------------

#true for enabled and false for disabilitate
enabled-a: true
confirmation-message: "&aYou sent a request for helpstaff to the staff!"
